version: '3.3'
services:
  mysql-db:
    image: mysql:8.0.28
    environment:
      MYSQL_DATABASE: 'reporting'
      MYSQL_ROOT_PASSWORD: 'admin-password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
  postgres-db:
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_USER=user
      - POSTGRESS_PASSWORD=admin-password
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
     
