version: '3'

services:
  # Lightdash service
  lightdash:
    image: lightdash/lightdash:latest
    ports:
      - "8080:8080"
    environment:
      LIGHTDASH_DB_TYPE: postgres
      LIGHTDASH_DB_HOST: postgres
      LIGHTDASH_DB_PORT: 5432
      LIGHTDASH_DB_NAME: lightdash
      LIGHTDASH_DB_USER: lightdash
      LIGHTDASH_DB_PASSWORD: lightdash_password
    depends_on:
      - postgres

  # PostgreSQL service
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: lightdash
      POSTGRES_USER: lightdash
      POSTGRES_PASSWORD: lightdash_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Druid service (adjust image and configuration as needed)
  druid:
    image: apache/incubator-druid:latest
    ports:
      - "8081:8081"
    volumes:
      - druid_data:/opt/druid/var
    environment:
      DRUID_XMX: "-Xmx512m"
      DRUID_XMS: "-Xms512m"
      DRUID_MAXNEWSIZE: "-Xmn256m"
      DRUID_HOSTNAME: druid
      DRUID_PORT: 8081

  # Apache Airflow service
  airflow:
    image: apache/airflow:latest
    ports:
      - "8082:8080"
    environment:
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql://airflow:airflow_password@postgres/airflow
      AIRFLOW__CORE__FERNET_KEY: "FernetKey"
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__WEBSERVER__EXPOSE_CONFIG: "True"
    depends_on:
      - postgres
    volumes:
      - airflow_data:/opt/airflow

volumes:
  postgres_data:
  druid_data:
  airflow_data: