version: '3'

services:
  # Lightdash service
  lightdash:
    image: lightdash/lightdash:latest
    ports:
      - "8080:8080"
    environment:
      LIGHTDASH_DB_TYPE: postgres
      LIGHTDASH_DB_HOST: postgres
      LIGHTDASH_DB_PORT: 5432
      LIGHTDASH_DB_NAME: ${POSTGRES_DB}
      LIGHTDASH_DB_USER: ${LIGHTDASH_POSTGRES_USER}
      LIGHTDASH_DB_PASSWORD: ${LIGHTDASH_POSTGRES_PASSWORD}
    depends_on:
      - postgres

  # PostgreSQL service 
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/postgres_entrypoint.sql:/docker-entrypoint-initdb.d/create_tables.sql


  # Apache Airflow service
  airflow:
    image: apache/airflow:latest
    ports:
      - "8082:8080"
    environment:
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql://airflow:airflow_password@postgres/airflow
      AIRFLOW__CORE__FERNET_KEY: "FernetKey"
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__WEBSERVER__EXPOSE_CONFIG: "True"
    depends_on:
      - postgres
    volumes:
      - airflow_data:/opt/airflow

  # FastAPI service
  fastapi:
    build:
      context: ./api/fastapi_app  # Path to your FastAPI app code
    ports:
      - "80:80"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      FASTAPI_DB_USER: ${FASTAPI_DB_USER}
      FASTAPI_DB_PASSWORD: ${FASTAPI_DB_PASSWORD}
      POSTGRES_HOST: postgres
    depends_on:
      - postgres

volumes:
  postgres_data:
  airflow_data:
